### ISSUE TITLE
Can you provide the download link for the data required for this pipeline?

### ISSUE THREAD

**Issue by xylapple2013** [EBI-Metagenomics/amplicon-pipeline#9]
Can you provide the download link for the data required for this pipeline?

**Comment by chrisAta** [comment]
Hello!

Thanks for your input - I have just uploaded the databases this pipeline uses [here](https://ftp.ebi.ac.uk/pub/databases/metagenomics/pipelines/tool-dbs/). The specific databases you need are:
- silva-ssu
- silva-lsu
- pr2
- unite
- itsonedb
- rfam

I will close this now, but let us know if you have any more questions!
